---
title: "Integrate datasets"
author: "jack"
editor_options: 
  chunk_output_type: console
---

```{r}
library(Seurat)
library(tidyverse)
library(harmony)

source("03-scripts/R/seq_functions.R")
```

```{r}
may <- LoadDataset("May2024")
dec <- LoadDataset("Dec2024_pilot")
```


# Examine un-integrated dataset
```{r combine}
Idents(may) <- may$subclass_name
Idents(dec) <- dec$subclass_name

comb_raw <- merge(may, y = dec, 
                  add.cell.ids = c("May2024", "Dec2024_pilot"),
                  merge.data = FALSE
                  )

# remove SCT assay
DefaultAssay(comb_raw) <- 'RNA'
comb_raw[['SCT']] <- NULL

# join counts
comb_raw[['RNA']] <- JoinLayers(comb_raw[['RNA']])
```

```{r turn dataset into a column}
run_vector <- comb_raw@meta.data |> 
  rownames_to_column(var = 'run') |> 
  mutate(run = str_sub(run, 1, 7)) |> 
  pull(run)

comb_raw$run <- run_vector
```

```{r}
comb <- comb_raw |> 
  NormalizeData(normalization.method = 'LogNormalize', scale.factor = 10000) |> 
  FindVariableFeatures() |> 
  ScaleData() |> 
  RunPCA(npcs = 50) |> 
  FindNeighbors(dims = 1:41) |> 
  FindClusters(resolution = 0.8) |> 
  RunUMAP(dims = 1:41)
```

```{r}
DimPlot(comb, group.by = 'run', pt.size = 1, shuffle = TRUE, seed = 17)
```


# Integrate dataset
```{r use harmony} 
comb <- RunHarmony(comb, group.by.vars = c('run'))
```

```{r}
comb <- comb |> 
  FindNeighbors(reduction = "harmony") |> 
  FindClusters(resolution = 0.8) |> 
  RunUMAP(reduction = 'harmony', dims = 1:41)
```

```{r}
subclass_colors <- LoadAllenColors()
activity_colors <- LoadActivityColors("Dec2024")

DimPlot(comb, reduction = 'umap', group.by = 'subclass_name', shuffle = TRUE, seed = 17, pt.size = 1) + 
  scale_color_manual(values=subclass_colors) + theme_void() + theme(legend.position = 'none')
DimPlot(comb, reduction = 'umap', group.by = 'run', shuffle = TRUE, seed = 17, pt.size = 1) + 
  theme_void() + theme(legend.position = 'none')
DimPlot(comb, reduction = 'umap', group.by = 'activity_condition', shuffle = TRUE, seed = 17, pt.size = 1) + 
  scale_color_manual(values=activity_colors) + theme_void() + theme(legend.position = 'none')
```

