---
title: "2025-03-28 workbook"
author: "jack"
editor: visual
---

# test read speed

```{r}
source('03-scripts/R/seq_functions.R')

# time loading of all nuclei
start_time <- Sys.time()
nuclei <- LoadDataset('Dec2024')
end_time <- Sys.time()
print(glue('Time to load dataset: {end_time - start_time}'))

# time loading of gigaclasses
start_time <- Sys.time()
nuclei_gigaclasses <- LoadDataset('Dec2024', as_gigaclasses = TRUE)
end_time <- Sys.time()
print(glue('Time to load dataset as gigaclasses: {end_time - start_time}'))
```

# circadian IEGs

```{r}
known_circadian_genes <- c(LoadGeneList('IEG'), 'Npas2')
mat_circadian <- GetAssayData(nuclei_subclass)
mat_circadian <- mat_circadian[known_circadian_genes,] |> t()
nuclei_subclass@meta.data <- nuclei_subclass@meta.data |> 
  mutate(ZT.collection = case_when(
    (ZT == 'ZT0' & activity_condition == 'EE6h') ~ 'ZT6',
    (ZT == 'ZT4' & activity_condition == 'EE6h') ~ 'ZT10',
    (ZT == 'ZT12' & activity_condition == 'EE6h') ~ 'ZT18',
    (ZT == 'ZT16' & activity_condition == 'EE6h') ~ 'ZT22',
    TRUE ~ ZT
  )) |> 
  mutate(ZT.collection = factor(ZT.collection, 
                                levels = c('ZT0', 'ZT4', 'ZT6', 'ZT10', 'ZT12', 'ZT16', 'ZT18', 'ZT22')))

# merge circadian gene expression with cell metadata
df_circadian <- as.matrix(mat_circadian) |> 
  as_tibble(rownames = 'barcode') |> 
  right_join(nuclei_subclass@meta.data) |> 
  # pivot_longer(cols = all_of(known_circadian_genes), names_to = 'gene', values_to = 'expression') |> 
  pivot_longer(cols = all_of(known_circadian_genes), names_to = 'gene', values_to = 'expression') |> 
  select(gene, barcode, ZT, activity_condition, subclass_name, expression) |> 
  calc_sem('mean_expression', c('ZT', 'subclass_name', 'gene')) |> 
  arrange(gene, subclass_name, ZT) |> 
  relocate(gene, subclass_name) |> 
  as_tibble()
df_circadian


# plot clock genes ----------------------------------------
for (gene_to_plot in known_circadian_genes) {
  p <- df_circadian |> 
    filter(gene == gene_to_plot) |>
  ggplot() +
    aes(x = ZT, y = mean_norm, group = subclass_name, color = subclass_name) +
    geom_line(linewidth = 2) +
    geom_errorbar(aes(ymin = mean_norm-sem_norm, ymax = mean_norm+sem_norm), 
                  linewidth = 2, width = 0.1) +
    geom_point(size = 5) +
    scale_color_manual(values = subclass_colors) +
    labs(title = glue('{gene_to_plot} in SE'),
         y = 'Normalized expression') +
    theme(
      legend.position = 'none',
      axis.text.x = element_text(size = 12, angle = 30),
      axis.title.y = element_text(size = 12),
      axis.title.x = element_blank(),
      plot.title = element_text(size = 12, hjust = 0.5)
    )
  print(p)
}
```

```{r}
tmp <- PseudobulkExpression(nuclei_subclass, 
                     group.by = c('sample', 'subclass_name', 'ZT'),
                     assay = 'RNA', layer = 'counts',
                     features = c(LoadGeneList('IEG'), LoadGeneList('circadian')),
                     return.seurat = T,
                     method = 'aggregate')
VlnPlot(tmp, 'Per1', group.by = 'subclass_name', split.by = 'ZT') +
  scale_fill_manual(values = LoadZTColors())
```

```{r}
library(patchwork)

# CA1
p1 <- DimPlot(nuclei |> subset(subclass_name == '016 CA1-ProS Glut' & activity_condition == 'SE'),
        group.by = 'ZT', pt.size = 2, shuffle = T) + 
  scale_color_manual(values = LoadZTColors()) +
  labs(title = 'CA1') +
  theme_void()

# DG
p2 <- DimPlot(nuclei |> subset(subclass_name == '037 DG Glut' & activity_condition == 'SE'),
        group.by = 'ZT', pt.size = 2, shuffle = T) + 
  scale_color_manual(values = LoadZTColors()) +
  labs(title = 'DG') +
  theme_void()

# Astro
p3 <- DimPlot(nuclei |> subset(subclass_name == '319 Astro-TE NN' & activity_condition == 'SE'),
        group.by = 'ZT', pt.size = 2, shuffle = T) + 
  scale_color_manual(values = LoadZTColors()) +
  labs(title = 'Astro') +
  theme_void()

# Oligo
p4 <- DimPlot(nuclei |> subset(subclass_name == '327 Oligo NN' & activity_condition == 'SE'),
        group.by = 'ZT', pt.size = 2, shuffle = T) + 
  scale_color_manual(values = LoadZTColors()) +
  labs(title = 'Oligo') +
  theme_void()
  
(p1+p2) / (p3+p4)
```

```{r}
source('03-scripts/R/seq_functions.R')
nuclei <- LoadDataset("Dec2024")
nuclei_ca1 <- nuclei |> subset(subclass_name == '016 CA1-ProS Glut' & activity_condition %in% c('SE', 'EE30m', 'EE6h'))
activity_mat <- GetAssayData(nuclei_ca1, 
                             assay = 'SCT', 
                             layer = 'counts')
activity_mat <- activity_mat[c(LoadGeneList(), LoadGeneList('circadian')), ] |> t()

# merge back with seurat metadata
df_expression <- activity_mat |> 
  as_tibble(rownames = 'barcode') |> 
  right_join(nuclei_ca1@meta.data) |> 
  pivot_longer(cols = all_of(c(LoadGeneList(), LoadGeneList('circadian'))),
               names_to = 'gene',
               values_to = 'expression')


```
