---
title: "2025_03_27 workbook"
---

# fc shrinkage comparison

```{r fc shrink}
res_apeglm <- results(dds, name = "activity_condition_EE30m_vs_SE") %>%
  lfcShrink(dds = dds, coef = 'activity_condition_EE30m_vs_SE', res = .) |> 
  as.data.frame() |>
  as_tibble(rownames = 'gene') |> 
  arrange(gene) |> 
  print()


res_ashr <- results(dds, name = "activity_condition_EE30m_vs_SE") %>%
  lfcShrink(dds = dds, coef = 'activity_condition_EE30m_vs_SE', res = ., type = 'ashr') |> 
  as.data.frame() |>
  as_tibble(rownames = 'gene') |> 
  arrange(gene) |> 
  print()

res_raw <- results(dds, name = "activity_condition_EE30m_vs_SE") |> 
  as.data.frame() |>
  as_tibble(rownames = 'gene') |> 
  arrange(gene) |> 
  print()

df_fc <- tibble(
  gene = res_ashr$gene,
  mean_exp= log10(res_raw$baseMean),
  sig = ifelse((res_raw$padj < 0.05 & abs(res_raw$log2FoldChange)>0.585), 'signif', 'not sig'), 
  apeglm_FC  = res_apeglm$log2FoldChange,
  ashr_FC    = res_ashr$log2FoldChange,
  raw_FC     = res_raw$log2FoldChange,
) |> 
  mutate(sig = factor(sig, levels = c('signif', 'not sig')))

base_plot <- function(data, y_var) {
  ggplot(data, aes(x = raw_FC, y = {{ y_var }}, color = mean_exp)) +
    geom_point(aes(fill = sig), shape = 21, size = 3, stroke = 1) +
    geom_line(
      data = tibble(x = c(-3, 3), y = c(-3, 3)), 
      aes(x, y), 
      inherit.aes = FALSE, 
      linetype = 2, 
      linewidth = 2, 
      color = 'white'
    ) +
    geom_hline(yintercept = c(-0.585, 0.585), linetype = 2, color = 'gray80') +
    geom_vline(xintercept = c(-0.585, 0.585), linetype = 2, color = 'gray80') +
    scale_color_viridis_c(option = 'B', limit = c(1, 4), oob = scales::squish) +
    theme_classic() +
    labs(x = 'raw log2FC', y = deparse(substitute(y_var))) +
    coord_fixed(xlim = c(-3,3)) +
    theme(
      legend.position = 'none',
      axis.title=element_text(size = 30),
      axis.text = element_text(size = 25),
      panel.background = element_rect(fill = 'black')
    )
}

p1 <- base_plot(df_fc, apeglm_FC)
p2 <- base_plot(df_fc, ashr_FC) + theme(legend.position = 'right')

p <- p1 + p2 + plot_annotation(title = 'Comparing shrunken FC values for EE30m-SE') &
  theme(plot.title = element_text(size = 30), legend.text = element_text(size = 12))
ggplotly(p)
```

# DG cluster plot (CRAB fig)

```{r DG cluster plot}
df_cluster_counts |> 
  filter(subclass_name == '037 DG Glut') |> 
  ungroup(supertype_name) |> 
  mutate(cluster_pct = cluster_count / sum(cluster_count) * 100) |> 
  arrange(activity_condition, cluster_name) |> 
  print(n=31)
```

# make pseudobulk seurat

```{r make pseudobulk seurat}
nuclei_pb <- AggregateExpression(
      nuclei_gigaclass,
      assays = 'RNA',
      # features = df_distinct_DEGs$gene,
      group.by = c("subclass_name", "activity_condition"),
      return.seurat = T
    )
Idents(nuclei_pb) <- nuclei_pb$activity_condition

for (subclass in unique(nuclei_pb$subclass_name)) {
nuclei_pb |> 
  subset(subclass_name == subclass) |> 
  FoldChange(
    features = df_distinct_DEGs$gene,
    cells.1 = 'EE30m',
    cells.2 = 'SE',
    fc.name = 'log2FoldChange'
  )
}


list_fc_gigaclass <- map(
  sort(unique(nuclei_pb$subclass_name)),
  function(subclass) {
    nuclei_pb |> 
      subset(subclass_name == subclass) |> 
      FoldChange(
        features = df_distinct_DEGs$gene,
        ident.1 = 'EE30m',
        ident.2 = 'SE',
        fc.name = 'log2FoldChange'
      ) |> 
      as_tibble(rownames = 'gene') |> 
      arrange(desc(log2FoldChange))
  }, # end fxn
  .progress = T
) |> 
  set_names(str_sub(sort(unique(nuclei_pb$subclass_name)), 2, -1))

VlnPlot(nuclei_pb, list_fc_gigaclass$`016 CA1-ProS Glut`$gene |> head())
```
