---
title: "DEGs among different cell types"
author: "jack"
editor_options: 
  chunk_output_type: console
---

```{r}
source("03-scripts/R/seq_functions.R")

library(Seurat)

library(dplyr)
library(readr)
library(glue)

library(patchwork)
library(ggplot2)
library(ggforce)
library(ggvenn)
library(ggrepel)
library(plotly)

library(ComplexHeatmap)
```

```{r}
condition_colors <- LoadConditionColors("May2024")
subclass_colors <- LoadAllenColors("subclass")
```

```{r}
nuclei <- LoadDataset("May2024", "combined")
```

```{r load DEGs for subclasses}
DEG_csv_dir <- "~/code/seq/data/DEGs/"
csv_fnames <- dir(DEG_csv_dir)

# load in all csvs containting cell_type_str
cell_type_str <- "016_CA1-ProS_Glut"
cell_type_str <- "319_Astro-TE_NN"
cell_type_fnames <- csv_fnames[grep(cell_type_str, csv_fnames)]
cell_type_fnames

# load in sex-specific genes for this cell type
sex_DEG_csv_dir <- "/Volumes/jack/yao2023/DGE/"
dimorphic_fnames <- dir(sex_DEG_csv_dir)
cell_type_dimorphic_fname <- dimorphic_fnames[grep(cell_type_str, dimorphic_fnames)]
dimorphic_genes <- read_csv(paste0(sex_DEG_csv_dir, cell_type_dimorphic_fname))

# read in genes, filtering out sex-specific genes for the cell type
d30m_vs_dSE <- read_csv(paste0(DEG_csv_dir, cell_type_str, '_d30m_vs_dSE.csv'))  |> filter(!gene %in% dimorphic_genes$gene)
d30m_vs_d6h <- read_csv(paste0(DEG_csv_dir, cell_type_str, '_d30m_vs_d6h.csv')) |> filter(!gene %in% dimorphic_genes$gene)

KA_vs_d30m <- read_csv(paste0(DEG_csv_dir, cell_type_str, '_KA_vs_d30m.csv')) |> filter(!gene %in% dimorphic_genes$gene)
KA_vs_dSE <- read_csv(paste0(DEG_csv_dir, cell_type_str, '_KA_vs_dSE.csv')) |> filter(!gene %in% dimorphic_genes$gene)
KA_vs_d6h <- read_csv(paste0(DEG_csv_dir, cell_type_str, '_KA_vs_d6h.csv')) |> filter(!gene %in% dimorphic_genes$gene)

d6h_vs_dSE <- read_csv(paste0(DEG_csv_dir, cell_type_str, '_d6h_vs_dSE.csv')) |> filter(!gene %in% dimorphic_genes$gene)

combined <- d30m_vs_dSE |> mutate(contrast = 'd30m_vs_dSE') |> 
  rbind(d30m_vs_d6h |> mutate(contrast = 'd30m_vs_d6h'))
  rbind(KA_vs_dSE |> mutate(contrast = 'KA_vs_dSE')) |>
  rbind(KA_vs_d30m |> mutate(contrast = 'KA_vs_d30m')) |>
  rbind(KA_vs_d6h |> mutate(contrast = 'KA_vs_d6h')) |>
  rbind(d6h_vs_dSE |> mutate(contrast = 'd6h_vs_dSE'))
```

```{r get all DEGs for a subclass}
subclasses <- read_csv("/Volumes/jack/yao2023/subclasses_to_use.csv") |> 
  pull(subclass_name)

# load all d30m vs dSE DEGs into a tibble
all_DEGs <- tibble()
for (subclass in subclasses) {
  subclass_fname <- gsub(" ", "_", subclass)
  subclass_fname <- gsub("/", "", subclass_fname)

  # load in sex-specific genes for this subclass
  sex_genes <- read_csv(glue("/Volumes/jack/yao2023/DGE/{subclass_fname}_DEGs.csv")) |> 
    pull(gene)
  
  # load in DEGs for this subclass; filter out sex genesseq/manuscript
  subclass_degs <- read_csv(glue("~/code/seq/data/DEGs/{subclass_fname}_d30m_vs_dSE.csv")) |> 
    filter(!gene %in% sex_genes) |> 
    mutate(subclass = subclass) |> 
    arrange(subclass, desc(avg_log2FC))

  all_DEGs <- rbind(all_DEGs, subclass_degs)
}

all_DEGs
```

```{r volcano plot for all subclasses}
ggplot(all_DEGs) +
  aes(x = avg_log2FC, y = -log10(p_val_adj), fill = subclass) +
  geom_point(shape = 21) +
  geom_label_repel(aes(label = gene)) +
  facet_wrap(~subclass)
```

For each subclass with 10 or more IEGs, get those IEGs and plot them

```{r coexpression plot}
plots <- list()

for (subclass_name in subclasses) {
  subclass_IEGs <- all_DEGs |> 
    filter(subclass == subclass_name) |>
    arrange(desc(avg_log2FC)) |>
    head(10) |>
    pull(gene) |> print()

    if (length(subclass_IEGs) < 4) {
      next
    } else if (subclass_name == "033 NP SUB Glut") {
      next
    }
      
  for (i in seq_along(names(condition_colors))) {
    # get current condition
    condition <- names(condition_colors)[i]

    # calculate gene-pair correlations
    corr_data <- GetCorrData(nuclei, condition, subclass_IEGs)

    # plot the gene-pair correlations
    p <- ggplot(corr_data) +
      aes(x = gene1, y = gene2, fill = corr_coef) +
      geom_tile(color = 'black') +
      scale_fill_gradient2(low = 'blue', high = 'red', midpoint = 0, 
        limits = c(-1, 1), 
        name = "Gene-pair\ncorrelation"
      ) +
      labs(title = glue("{subclass_name}: {condition}")) +
      coord_fixed() +
      theme(
        panel.border = element_blank(),
        panel.background = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        plot.title = element_text(size = 12),
        axis.text.x = element_text(angle = 45, hjust = 1, size = 8),
        axis.text.y = element_text(size = 8),
        axis.ticks = element_blank(),
        legend.position = 'none',
        )

    plots <- c(plots, list(p))
  }
}

wrap_plots(plots, nrow = 4, byrow = FALSE)
```

I'm interested in the spatial distribution of IEG expression, so let's load some of that data in.

```{r load in MERFISH meta}
allen_taxonomy <- read_csv("~/code/seq/misc/allen_taxonomy.csv")
meta_merfish <- read_csv("/Volumes/jack/zhang2023/rawdata/cell_metadata.csv")

meta_merfish <- meta_merfish |> 
  left_join(allen_taxonomy, by = "cluster_alias") |> 
  filter(low_quality_mapping == FALSE) |> print()
```

```{r plotly}
cluster_colors <- LoadAllenColors(clade="cluster")
subclass_colors <- LoadAllenColors(clade="subclass")
supertype_colors <- LoadAllenColors(clade = "supertype")

meta_merfish |> 
  filter(subclass %in% c(
    "016 CA1-ProS Glut"
    # "017 CA3 Glut",
    # "037 DG Glut"
  )) |>
  # use plotly to plot in 3-D
  plot_ly(
    x = ~x, y = ~y, z = ~z,
    color = ~supertype,
    colors = supertype_colors,
    # color = ~subclass,
    # colors = subclass_colors,
    type = "scatter3d",
    mode = "markers",
    marker = list(size = 5)
    # turn off axis and grid labels
  )
```

```{r supertype distro}
# distribution along A-P (z) axis
p_ap <- meta_merfish |> 
  filter(subclass == '016 CA1-ProS Glut') |>
  filter(x < 9| x > 2.5) |>   # anything outside this range is mis-classified
  filter(y < 8.1 | y > 2.9 ) |>   # anything outside is mis-classified
  filter(z < 8 & z > 4) |>   # anything outside is mis-classified
  group_by(z, supertype) |> 
  summarise(n = n()) |>
  mutate(percent = n / sum(n)) |> 
ggplot() +
  geom_area(aes(x = z, y = percent, fill = supertype), position = 'fill') +
  geom_vline(xintercept = seq(7.5,4,-0.2), color = 'white', linetype = 2, alpha = 0.3) +
  scale_fill_manual(values = supertype_colors) +
  scale_x_reverse() +
  labs(title = "Supertypes along A-P axis",
    x = "<-- anterior / posterior -->", y = "Proportion of cells"
  ) +
  theme(
    plot.title = element_text(size = 30),
    axis.title.x = element_text(size = 30),
    axis.title.y = element_text(size = 30),
    legend.position = c(0.2, 0.25),
  )

# distribution along D-V (y) axis
meta_temp <- meta_merfish |> 
  filter(subclass == '016 CA1-ProS Glut') |>
  filter(x < 9| x > 2.5) |>   # anything outside this range is mis-classified
  filter(y < 8.1 | y > 2.9 ) |>   # anything outside is mis-classified
  filter(z < 8 & z > 4) |>   # anything outside is mis-classified
  mutate(ycut = cut(y, breaks = seq(2.9, 8.1, 0.2)))
meta_temp <- meta_temp |>
  mutate(yy = as.numeric(substr(as.character(ycut), 2, 4)))  # change to number
p_dv <- meta_temp |>  
  group_by(yy, supertype) |> 
  summarise(n = n()) |>
  mutate(percent = n / sum(n)) |> 
ggplot() +
  geom_area(aes(x = yy, y = percent, fill = supertype), position = 'fill') +
  geom_vline(xintercept = seq(7.8,3.2,-0.5), color = 'white', linetype = 2, alpha = 0.3) +
  scale_x_reverse() +
  coord_flip() +
  scale_fill_manual(values = supertype_colors) +
  labs(title = "Supertypes along D-V axis",
    x = "<-- ventral / dorsal -->", y = "Proportion of cells"
  ) +
  theme(
    plot.title = element_text(size = 30),
    axis.title.x = element_text(size = 30),
    axis.title.y = element_text(size = 30),
    legend.position = 'none',
  )

p_ap + p_dv + plot_layout(widths = c(2,1))
```

```{r cluster distro}
cluster_colors <- LoadAllenColors(clade = "cluster")

ca1_merfish <- meta_merfish |> 
  filter(subclass == "016 CA1-ProS Glut") |> 
  filter(x < 9| x > 2.5) |>       # anything outside this range is mis-classified
  filter(y < 8.1 | y > 2.9 ) |>   # anything outside is mis-classified
  filter(z < 8 & z > 4)           # anything outside is mis-classified

# distribution along A-P (z) axis
p_ap <- ca1_merfish |> 
  group_by(z, cluster) |> 
  summarise(n = n()) |>
  mutate(percent = n / sum(n)) |> 
ggplot() +
  geom_area(aes(x = z, y = percent, fill = cluster), position = 'fill') +
  geom_vline(xintercept = seq(7.5,4,-0.2), color = 'white', linetype = 2, alpha = 0.3) +
  scale_fill_manual(values = cluster_colors) +
  scale_x_reverse() +
  labs(title = "Clusters along A-P axis",
    x = "<-- anterior / posterior -->", y = "Proportion of cells"
  ) +
  theme(
    plot.title = element_text(size = 30),
    axis.title.x = element_text(size = 30),
    axis.title.y = element_text(size = 30),
    legend.position = c(0.2, 0.25),
  )

# distribution along D-V (y) axis
meta_temp <- ca1_merfish |> 
  mutate(ycut = cut(y, breaks = seq(2.9, 8.1, 0.2)))
meta_temp <- meta_temp |>
  mutate(yy = as.numeric(substr(as.character(ycut), 2, 4)))  # change to number
p_dv <- meta_temp |>  
  group_by(yy, cluster) |> 
  summarise(n = n()) |>
  mutate(percent = n / sum(n)) |> 
ggplot() +
  geom_area(aes(x = yy, y = percent, fill = cluster), position = 'fill') +
  geom_vline(xintercept = seq(7.8,3.2,-0.5), color = 'white', linetype = 2, alpha = 0.3) +
  scale_x_reverse() +
  coord_flip() +
  scale_fill_manual(values = cluster_colors) +
  labs(title = "Clusters along D-V axis",
    x = "<-- ventral / dorsal -->", y = "Proportion of cells"
  ) +
  theme(
    plot.title = element_text(size = 30),
    axis.title.x = element_text(size = 30),
    axis.title.y = element_text(size = 30),
    legend.position = 'none',
  )

p_ap + p_dv + plot_layout(widths = c(2,1))
```

```{r distro by IEG}
# find proportion of cells expressing Npas4 above 0 in each supertype
df_active_cells <- FindActiveCells(nuclei, gene_type='IEG') |>
  pivot_longer(cols = c(num_upregd_IEGs:last_col(), -num_upregd_IEGs), names_to = "gene", values_to = "expression") |>
  mutate(is_expressing = expression > 0) |> 
  right_join(nuclei@meta.data, by = c("cell" = "bc_wells", "condition" = "condition")) |> 
  filter(subclass_name == '016 CA1-ProS Glut')

df_supertype_active  <- df_active_cells |>
  group_by(supertype_name, condition) |> 
  summarise(fraction_active = sum(active_binary) / n()) |> print()


# plot activation by supertype
df_active_cells |> 
  left_join(df_supertype_active, by = c("supertype_name", "condition")) |> 
ggplot() +
  aes(x = supertype_name, y = num_upregd_IEGs, fill = condition) +
  geom_jitter(shape = 21, size = 1.5, alpha = 0.5) +
  geom_hline(yintercept = 2.5) +
  scale_fill_manual(values = condition_colors) +
  scale_y_continuous(limits = c(-0.5, 10)) +
  labs(title = "Activation by supertype",
    x = "Supertype", y = "IEGs with expression\n>90th percentile") +
  theme(
    plot.title = element_text(size = 30),
    axis.title.x = element_text(size = 30),
    axis.title.y = element_text(size = 30),
    strip.text = element_text(size = 18),
    legend.position = 'none',
  ) +
  facet_wrap(~condition)


# plot active cells by supertype along anatomical axes
ca1_merfish |> 
  group_by(z, supertype) |>  
  summarise(n = n()) |> 
  mutate(composition = n / sum(n)) |> 
  left_join(df_supertype_active, by = c("supertype" = "supertype_name")) |> 
  mutate(height = composition * fraction_active) |>
ggplot() +
  geom_area(aes(x = z, y = height, fill = supertype), position = 'stack') +
  geom_vline(xintercept = seq(7.5,4,-0.2), color = 'white', linetype = 2, alpha = 0.3) +
  scale_fill_manual(values = supertype_colors) +
  scale_x_reverse() +
  scale_y_continuous(limits = c(0, 1)) +
  labs(title = "Active CA1 cells along A-P axis",
    x = "<-- anterior / posterior -->", y = "Proportion of active cells by supertype"
  ) +
  theme(
    plot.title = element_text(size = 30),
    axis.title.x = element_text(size = 30),
    axis.title.y = element_text(size = 30),
    strip.text = element_text(size = 18),
    legend.position = c(0.9, 0.9),
  ) +
  facet_wrap(~condition)
```
